# Generated by Django 2.1.5 on 2019-01-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='slug',
            field=models.SlugField(default='this-is-a-slug', unique=True),
            preserve_default=False,
        ),
    ]
