# Generated by Django 2.1.5 on 2019-01-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_lot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
